- hosts: RU

  vars:
   nginx_port: 1800
   root_dir: /etc/nginx
  
  tasks:
   - name: install nginx
     ansible.builtin.apt:
      name: nginx
      state: present
      update_cache: no
     become: yes
    
   - name: copy html
     ansible.builtin.template:
      src: files/index.html
      dest: /usr/share/nginx/html/index.html
     notify:
      - restart nginx
     become: yes
     tags: html
    
   - name: copy nginx config
     ansible.builtin.template:
      src: files/nginx.conf
      dest: "{{root_dir}}/nginx.conf"
     notify:
      - restart nginx
     become: yes
    
  handlers:
   - name: restart nginx
     ansible.builtin.service:
      name: nginx
      state: reloaded
     become: yes
       
